// Generates src/core/dmc-data.ts from the vetted raw DMC dataset.
// Run with: npm run build:dmc
//
// Source data: assets/dmc-source.json (factual DMC floss reference colors,
// derived from github.com/seanockert/rgb-to-dmc). DMC color numbers, names and
// approximate RGB values are factual reference data used for interoperability.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const raw = JSON.parse(readFileSync(join(root, 'assets/dmc-source.json'), 'utf8'));

const seen = new Set();
const colors = [];
for (const c of raw) {
  const code = String(c.floss).trim();
  const name = String(c.description).trim();
  const r = Number(c.r);
  const g = Number(c.g);
  const b = Number(c.b);
  if (!code || seen.has(code)) throw new Error(`bad/duplicate floss code: ${code}`);
  for (const v of [r, g, b]) {
    if (!Number.isInteger(v) || v < 0 || v > 255) throw new Error(`bad rgb for ${code}`);
  }
  seen.add(code);
  colors.push({ code, name, r, g, b });
}

colors.sort((a, b) => a.code.localeCompare(b.code, 'en', { numeric: true }));

const lines = colors.map(
  (c) => `  { code: ${JSON.stringify(c.code)}, name: ${JSON.stringify(c.name)}, r: ${c.r}, g: ${c.g}, b: ${c.b} },`,
);

const out = `// AUTO-GENERATED by scripts/build-dmc.mjs — do not edit by hand.
// ${colors.length} DMC embroidery floss colors (factual reference data).
// Source: github.com/seanockert/rgb-to-dmc

export interface DmcColor {
  /** DMC floss code, e.g. "310", "B5200", "White". */
  code: string;
  /** Human-readable color name. */
  name: string;
  r: number;
  g: number;
  b: number;
}

export const DMC_COLORS: readonly DmcColor[] = [
${lines.join('\n')}
];
`;

writeFileSync(join(root, 'src/core/dmc-data.ts'), out);
console.log(`Wrote src/core/dmc-data.ts with ${colors.length} colors.`);
